fix(check): Use tailscale status --json (#42)
* fix(check): Use tailscale status --json

* fix(check): Check 3 times before failing

* fix(check): Typo

* fix(check): Exit on success

diff --git a/action.yaml b/action.yaml
--- a/action.yaml
+++ b/action.yaml
@@ -36,10 +36,6 @@ inputs:
   ssh-user:
     description: "The SSH username to use when logging into your Docker host."
     required: true
-  ts-check-timeout:
-    default: "300"
-    description: "The timeout value for the Tailscale connectivity check in seconds."
-    required: false
   ts-oauth-client-id:
     description: "Your Tailscale OAuth Client ID."
     required: true
@@ -69,8 +65,14 @@ runs:
       id: check-connectivity
       run: |
         set -ex
-        sleep 10
-        tailscale ping --c=30 --timeout=1s --until-direct --verbose ${{ inputs.ssh-host }}
+        for i in {1..3}; do
+          sleep 10
+          [ "$(tailscale status --json | jq -r '.Self.Online')" = 'true' ] && echo "Check $i: Tailscale is online!" && exit 0 || echo "Check $i: Tailscale is offline!"
+          if [ $i = 3 ]; then
+            echo "ERROR: Tailscale is offline after 3 checks, exiting..."
+            exit 1
+          fi
+        done
       shell: bash
     - name: Run `ssh-keyscan`
       id: ssh-keyscan
